### ISSUE TITLE
Add quill-magic-url

### ISSUE THREAD

**Issue by visualjerk** [quilljs/awesome-quill#2]
Hi there and thanks for your awesome work!

After testing quill-auto-links it turns out that it didn't listen for enter and tab key, as one would expect. Because a major rewrite was necessary in order for these features to be added, I created a new module for it: [https://github.com/visualjerk/quill-magic-url](https://github.com/visualjerk/quill-magic-url)

Right now it listens for paste events and typing events with the enter, tab or space key.

I would appreciate if you add the new module to the list.

**Comment by patleeman** [comment]
Hey @visualjerk, thanks for submitting a new module! Can you create a pull request and add your module?

Here are the [contribution guidelines](https://github.com/quilljs/awesome-quill/blob/master/CONTRIBUTING.md).

**Comment by patleeman** [comment]
https://github.com/quilljs/awesome-quill/pull/3 Merged. Closing issue.
