### ISSUE TITLE
Word spelling is wrong

### ISSUE THREAD

**Issue by kagol** [quilljs/awesome-quill#30]
"surpport" should be "support".
![image](https://user-images.githubusercontent.com/9566362/65577297-1c11bb00-dfa6-11e9-903a-a4f8f48f36b4.png)

**Comment by volser** [comment]
@jhchen is this repo still live? you did not merge PR last 6 months...

**Comment by patleeman** [comment]
Sorry, been pretty negligent of PRs. Merged
