### ISSUE TITLE
Proposal: Quill Paste Smart plugin

### ISSUE THREAD

**Issue by artem-schander** [quilljs/awesome-quill#39]
Hi, many thanks for the awesome list :)

I have just released a [plugin](https://www.npmjs.com/package/quill-paste-smart) that - I think - would complement the list well.
It takes care of messy markup before pasting it into the editor. The cool thing is that it detects the supported tags and attributes by its own.
However, if you do not think it belongs here, I could understand that :) But if you think otherwise, I would be happy to see it in your list.
BTW. there are two more plugins in the pipeline. An extended link module and an icon collection based on font awesome.

**Comment by patleeman** [comment]
The list is pretty open. If you want to add your plugin just [review the contribution doc](https://github.com/quilljs/awesome-quill/blob/master/CONTRIBUTING.md)

**Comment by artem-schander** [comment]
Ok, thanks.
